# Spring config
spring:
  application:
    name: quote-service
  # Spring boot admin config
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8060/admin
        username: "admin"
        password: "1234"
        period: 60000
        auto-registration: true
        auto-deregistration: true
        register-once: false
  cloud:
    discovery:
      enabled: true

# Server config
server:
  http2:
    enabled: true
  servlet:
    context-path: /quotes/rest
  port: 8081
  use-forward-headers: true

# Application monitor info
info:
  app:
    name: Quote Service
    description: Rest service for read quotes
    environment: unknown

# Application monitor
management:
  security:
    enabled: false
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: auditevents,caches,configprops,env,health,info,metrics,scheduledtasks,shutdown,sessions
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  metrics:
    cache:
      instrument-cache: true

# Eureka
eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    metadata-map:
      startup: ${random.int}
  instance:
    hostname: localhost:${server.port}
    home-page-url: http://${eureka.instance.hostname}${server.servlet.context-path}/swagger-ui.html
    status-page-url-path: ${server.servlet.context-path}/monitor
    health-check-url-path: ${server.servlet.context-path}/monitor/health
    preferIpAddress: true