# Spring config
spring:
  application:
    name: Quotes
  # Spring boot admin config
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8060
        username: "admin"
        password: "1234"
        period: 600000
        auto-registration: true
        register-once: false

# Server config
server:
  http2:
    enabled: true
  servlet:
    contextPath: /quotes/rest
  port: 8080
  use-forward-headers: true

# Application monitor
management:
  security:
    enabled: false
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: auditevents,caches,configprops,env,health,info,metrics,scheduledtasks,shutdown,sessions
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  metrics:
    cache:
      instrument-cache: true

# Application monitor info
info:
  app:
    name: Quotes
    description: Rest service for read quotes
    environment: unknown